# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d353014652d4c2f1aab29fc80769c9fc6127558b50aa8e081885d6cff3396aeebe0483600ee098e002ffae866c11c198dfdf3be593471c5363f90434561af78

test:
  secret_key_base: 65a033ae8a9eb4c44105b96396fd01b58cd81f0c033a880cf0a2a4b64a0bb732cb464a425e38336101db8c8b6a0574a5e13a7460730cd0c31d652c213900a61f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
