# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5d54524a6e4aa660c544fb6482e273580b08008077750ee52862b84d387d24c7c0863560caa0309c828dab88124f68eb1442e53923a8ddbb7cd87c6dc67fef9

test:
  secret_key_base: 0cb608027c07513028dea01a968ea30ab68cb6e4f5ab4474eb31faee1a9f654636567fd975c55686594a52e0f6daf2f342897f63598ba1711d15aa39bc6781af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
