# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b8e333901cc770d711027e1457e536d0b014cd9d0fbf2078761a3508945a77e76b93b056ba1857be6711749787eb1ec4dcb5b8f2bebf130dcaaad2d5540c9a7

test:
  secret_key_base: fb0e38831a0730d851915dacdeed4780952ec14633703d55ebf6999c9ba0173cafdc5e36a915cc5815f1c993fde28349730bba968d24d0a1df00fb4a58ffd5c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
