# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af22c52003074dd736166113bbb598d2a11c6016da4d83d14b7ca962eeef2c8a2be035bd487f60dc02db307abd4b49d5068e2f2698b21df8112c43716ea8d856

test:
  secret_key_base: ca1f24fbb1259c5da6b505fbfdf64703a9562d4ca7e502031dd6ddd1a3b0fcbab0eade0260ce0e4f3665ce0c8befcec65ab9f99d1b7286469b156efb2d85d061

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
